name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Copyleaks ai detection
      uses: ./.github/actions/ai-detection
      with:
        copyleaks_account: ${{ secrets.COPYLEAKS_ACCOUNT }}
        copyleaks_api_key: ${{ secrets.COPYLEAKS_API_KEY }}
        installation_id: ${{ secrets.INSTALLATION_ID }}

